-- MySQL Script generated by MySQL Workbench
-- Sat Aug 31 19:44:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarioFinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarioFinal` (
  `idUsuarioFinal` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(8) NULL,
  `email` VARCHAR(45) NULL,
  `contrasena` LONGTEXT NULL,
  `direccion` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `estado` ENUM('activo', 'inactivo', 'baneado') NULL,
  PRIMARY KEY (`idUsuarioFinal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`superAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`superAdmin` (
  `idsuperAdmin` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `contrasena` LONGTEXT NULL,
  PRIMARY KEY (`idsuperAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zonas` (
  `idzonas` INT NOT NULL,
  `nombre_zona` VARCHAR(45) NULL,
  PRIMARY KEY (`idzonas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adminZonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adminZonal` (
  `idadminZonal` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(8) NULL,
  `email` VARCHAR(45) NULL,
  `contrasena` LONGTEXT NULL,
  `zona_id` INT NULL,
  `telefono` VARCHAR(9) NULL,
  PRIMARY KEY (`idadminZonal`),
  INDEX `zona_id_idx` (`zona_id` ASC) VISIBLE,
  CONSTRAINT `zona_id`
    FOREIGN KEY (`zona_id`)
    REFERENCES `mydb`.`zonas` (`idzonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agente` (
  `idagente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(8) NULL,
  `email` VARCHAR(45) NULL,
  `contrasena` LONGTEXT NULL,
  `zona_id` INT NULL,
  `telefono` VARCHAR(9) NULL,
  `codigo_aduana` VARCHAR(4) NULL,
  `ruc` VARCHAR(11) NULL,
  `razon_social` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  `codigo_juridisccion` VARCHAR(3) NULL,
  PRIMARY KEY (`idagente`),
  INDEX `zona_id_idx` (`zona_id` ASC) VISIBLE,
  CONSTRAINT `zona_id`
    FOREIGN KEY (`zona_id`)
    REFERENCES `mydb`.`zonas` (`idzonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `idproveedores` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono_contacto` VARCHAR(45) NULL,
  `ruc` VARCHAR(11) NULL,
  `dni` VARCHAR(8) NULL,
  `nombre_tienda` VARCHAR(45) NULL,
  `estado` ENUM('activo', 'inactivo', 'baneado') NULL,
  PRIMARY KEY (`idproveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `idproductos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `precio` DECIMAL(10,2) NULL,
  `costo_envio` DECIMAL(10,2) NULL,
  `cantidad_disponible` INT NULL,
  `zona_id` INT NULL,
  `proveedor_id` INT NULL,
  `modelos` VARCHAR(100) NULL,
  `colores` VARCHAR(100) NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `zonas_id_idx` (`zona_id` ASC) VISIBLE,
  INDEX `proveedor_id_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `zonas_id`
    FOREIGN KEY (`zona_id`)
    REFERENCES `mydb`.`zonas` (`idzonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proveedor_id`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `mydb`.`proveedores` (`idproveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordenes` (
  `idordenes` INT NOT NULL,
  `usuario_id` INT NULL,
  `estado` ENUM('Creado', 'En Validación', 'En Proceso', 'Arribo al País', 'En Aduanas', 'En Ruta', 'Recibido') NULL,
  `fecha_creacion` DATE NULL,
  `direccion_envio` TEXT(100) NULL,
  `total` DECIMAL(10,2) NULL,
  `metodo_pago` ENUM('tarjeta') NULL,
  `agente_id` INT NULL,
  PRIMARY KEY (`idordenes`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `agente_id_idx` (`agente_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarioFinal` (`idUsuarioFinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `agente_id`
    FOREIGN KEY (`agente_id`)
    REFERENCES `mydb`.`agente` (`idagente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detallesOrden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detallesOrden` (
  `iddetallesOrden` INT NOT NULL,
  `id_orden` INT NULL,
  `id_producto` INT NULL,
  `cantidad` INT NULL,
  `precio_unitario` DECIMAL(10,2) NULL,
  `subtotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`iddetallesOrden`),
  INDEX `id_orden_idx` (`id_orden` ASC) VISIBLE,
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_orden`
    FOREIGN KEY (`id_orden`)
    REFERENCES `mydb`.`ordenes` (`idordenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resenas` (
  `idresenas` INT NOT NULL,
  `usuario_id` INT NULL,
  `producto_id` INT NULL,
  `comentario` MEDIUMTEXT NULL,
  `satisfaccion` INT NULL,
  `fecha_resena` DATE NULL,
  `atencion_agente` INT NULL,
  `buena_calidad` TINYINT NULL,
  `se_recibio_rapido` INT NULL,
  PRIMARY KEY (`idresenas`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `producto_id_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarioFinal` (`idUsuarioFinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distritos` (
  `iddistrito` INT NOT NULL,
  `id_zona` INT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`iddistrito`),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `mydb`.`zonas` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
